pragma config(Motor,  port1,           FrontRight,    tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port2,           BackRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           FrontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           BackLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           HDrive,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           TopRightShooter, tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port7,           TopLeftShooter, tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           BottomRightShooter, tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port9,           BottomLeftShooter, tmotorVex393HighSpeed_MC29, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!


void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	while (1 == 1)
	{
		motor[port1] = vexRT[Ch2];
		motor[port2] = vexRT[Ch2];
		motor[port3] = vexRT[Ch3];
		motor[port4] = vexRT[Ch3];

		if(vexRT[Btn5U] == 1)
		{
			motor[port5] = 90;
		}
		else if(vexRT[Btn6U] == 1)
		{
			motor[port5] = -90;
		}
		else if(vexRT[Btn5U] == 0)
		{
			motor[port5] = 0;
	  }

	  if(vexRT[Btn8D] == 1)
	  {
	  	motor[port6] = 100;
	  	motor[port7] = 100;
	  	motor[port8] = 100;
	  	motor[port9] = 100;
	  }
	  else if(vexRT[Btn8R] == 1)
	  {
	  	motor[port6] = 0;
	  	motor[port7] = 0;
	  	motor[port8] = 0;
	  	motor[port9] = 0;
	  }
 }
}
