#pragma config(Motor,  port1,           FRD,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           BRD,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           FLD,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BLD,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           HD,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           TRF,           tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           TLF,           tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           BRF,           tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           BLF,           tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//Pre-Autonomous
void pre_auton()
{
	bStopTasksBetweenModes = true;
}

//Autonomous
task autonomous()
{
	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

//User Control
task usercontrol()
{
	while (true)
	{
		//Drive
		motor[FRD] = vexRT[Ch2];
		motor[BRD] = vexRT[Ch2];
		motor[FLD] = vexRT[Ch3];
		motor[BLD] = vexRT[Ch3];

		//H-Drive
		if(vexRT[Btn5U] == 1)
		{
			motor[HD] = 90;
		}
		else if(vexRT[Btn6U] == 1)
		{
			motor[HD] = -90;
		}
		else if(vexRT[Btn5U] == 0)
		{
			motor[HD] = 0;
		}

		//Fly Wheel
		if(vexRT[Btn8D] == 1)
		{
			motor[TRF] = 100;
			motor[TLF] = 100;
			motor[BRF] = 100;
			motor[BLF] = 100;
		}
		else if(vexRT[Btn8R] == 1)
		{
			motor[TRF] = 0;
			motor[TLF] = 0;
			motor[BRF] = 0;
			motor[BLF] = 0;
		}
	}
}
