#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           B,             tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           RD,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LD,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           BRF,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           TRF,           tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port6,           BLF,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           TLF,           tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//Pre-Autonomous
void pre_auton()
{
	bStopTasksBetweenModes = true;
}

//Autonomous
task autonomous()
{
	{
		/*
		*/
	}
}

//User Control
task usercontrol()
{
	while (true)
	{
		//Drive
		motor[LD]  = (vexRT[Ch1] + vexRT[Ch3])/2;  // (y + x)/2
		motor[RD] = (vexRT[Ch1] - vexRT[Ch3])/2;  // (y - x)/2


		//Belt
		if(vexRT[Btn6U] == 1)
		{
			motor[B] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[B] = -127;
		}
		else
		{
			motor[B] = 0;
		}


		//Fly Wheel 90 Speed
		if(vexRT[Btn8R] == 1)
		{
			motor[TRF] = 90;
			motor[TLF] = 90;
			motor[BRF] = 90;
			motor[BLF] = 90;
		}
		else if(vexRT[Btn8D] == 1)
		{
			motor[TRF] = 0;
			motor[TLF] = 0;
			motor[BRF] = 0;
			motor[BLF] = 0;
		}

		//Fly Wheel 85 Speed
		if(vexRT[Btn8U] == 1)
		{
			motor[TRF] = 85;
			motor[TLF] = 85;
			motor[BRF] = 85;
			motor[BLF] = 85;
		}
		else if(vexRT[Btn8D] == 1)
		{
			motor[TRF] = 0;
			motor[TLF] = 0;
			motor[BRF] = 0;
			motor[BLF] = 0;
		}

		//Fly Wheel 80 Speed
		if(vexRT[Btn8L] == 1)
		{
			motor[TRF] = 80;
			motor[TLF] = 80;
			motor[BRF] = 80;
			motor[BLF] = 80;
		}
		else if(vexRT[Btn8D] == 1)
		{
			motor[TRF] = 0;
			motor[TLF] = 0;
			motor[BRF] = 0;
			motor[BLF] = 0;
		}
	}
}
